# Generated by Django 5.2.13 on 2026-04-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emotionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionhistory',
            name='confidence',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emotionhistory',
            name='time_slot',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emotionhistory',
            name='username',
            field=models.CharField(default='guest', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emotionhistory',
            name='emotion',
            field=models.CharField(max_length=30),
        ),
    ]
