# Generated by Django 5.2.13 on 2026-04-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emotionhistory_confidence_emotionhistory_time_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotionhistory',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='emotionhistory',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='emotionhistory',
            name='username',
        ),
        migrations.AlterField(
            model_name='emotionhistory',
            name='emotion',
            field=models.CharField(max_length=50),
        ),
    ]
